### ISSUE TITLE
Potential improvements on compiler equivalence check

### ISSUE THREAD

**Issue by yxliang01** [JoranHonig/vertigo#14]
@JoranHonig I'm wondering whether the comparison of bytecodes is after stripping the metadata in the bytecode that are not semantic related? As I don't see any code doing so. 
Also, optimization is currently not enforced which should already eliminate lots of the functionally equivalent ones.

**Comment by JoranHonig** [comment]
@yxliang01 this is just an implementation of trivial compiler equivalence. 
There are other approaches that have higher precision, but they aren't implemented yet.

> I'm wondering whether the comparison of bytecodes is after stripping the metadata in the bytecode that are not semantic related? As I don't see any code doing so.

There is indeed no such behaviour. Such an approach is definately possible, I'm not sure that it has/hasn't been explored in previous research though.

> Also, optimization is currently not enforced which should already eliminate lots of the functionally equivalent ones.

The implementation is not very clean, but optmisation is enforced by the following line
https://github.com/JoranHonig/vertigo/blob/master/eth_vertigo/test_runner/truffle/truffle_runner.py#L26

**Comment by JoranHonig** [comment]
An interesting project would be to use [mythril](https://github.com/ConsenSys/mythril), to find equivalent mutants or to generate tests to cover non-equivalent mutations.

**Comment by yxliang01** [comment]
@JoranHonig Hmm, I'm wondering, have you observed two different source code hitting this equivalence check? If you don't strip the source code metadata from the compiled bytecode, two different source code of the same semantic should end up with different bytecode since the metadata contains hash of the source code of some sort.

**Comment by yxliang01** [comment]
By the way, using mythril to do equivalent checking sounds a bit like [symdiff](https://www.microsoft.com/en-us/research/project/symdiff-differential-program-verifier/)

**Comment by JoranHonig** [comment]
@yxliang01 Ah, I understand what you mean.
Vertigo assumes that a mutant is equivalent if the bytecode for all contracts in the original state and for the mutant are exactly equivalent.
The other output from the compiler (including the metadata field) is ignored.

**Comment by yxliang01** [comment]
@JoranHonig Hmm, I'm unsure whether we are talking about the same thing... By metadata, I meant the `bzzr`-encoded swarm source hash which is appended to the bytecode outputted by `solc` which can't even be disabled. This swarm source hash is computed from the source code text. So, two semantic equivalent but syntactically different sol files will have different bytecode outputted from the `solc`.

**Comment by JoranHonig** [comment]
@yxliang01 I did not know about this "feature" in sollc.
You are totally right, this should be stripped from the bytecode

**Comment by JoranHonig** [comment]
@yxliang01 I have created a pr which removes the hash metadata from the bytecode
